version: "3" # specify docker-compose version

# define the services/containers to be run
services:
    # app: # node project
    #     build: . # specify the directory of the Dockerfile
    #     ports:
    #         - "3000:3000" # specify ports forwarding
    #     container_name: node-app
    #     restart: always
    #     links:
    #         - database # link this service to the database service
    database: # name of the MongoDB service
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
        container_name: database
